export const BLOGINFOS_LOADING = 'BLOGINFOS_LOADING';
export const BLOGINFOS_FAILED = 'BLOGINFOS_FAILED';
export const ADD_BLOGINFOS = 'ADD_BLOGINFOS';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';